# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  fileSystems."/" =
    { device = "tmpfs";
      fsType = "tmpfs";
      options = [ "noatime" "mode=755"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0790-3BA0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3b4d02e9-a1fa-43a2-b8f5-97f1de5baa63";
      fsType = "btrfs";
      options = [ "subvol=@home" "default" "noatime" "ssd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3b4d02e9-a1fa-43a2-b8f5-97f1de5baa63";
      fsType = "btrfs";
      options = [ "subvol=@nix" "default" "noatime" "ssd" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/disk/by-uuid/3b4d02e9-a1fa-43a2-b8f5-97f1de5baa63";
      fsType = "btrfs";
      options = [ "subvol=@persistent" "default" "noatime" "ssd" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/3b4d02e9-a1fa-43a2-b8f5-97f1de5baa63";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "default" "noatime" "ssd" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/3b4d02e9-a1fa-43a2-b8f5-97f1de5baa63";
      fsType = "btrfs";
      options = [ "subvol=@" "default" "noatime" "ssd" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/3b4d02e9-a1fa-43a2-b8f5-97f1de5baa63";
      fsType = "btrfs";
      options = [ "subvol=@swap" "default" "noatime" "ssd" ];
    };

  fileSystems."/btr_pool" =
    { device = "/dev/disk/by-uuid/3b4d02e9-a1fa-43a2-b8f5-97f1de5baa63";
      fsType = "btrfs";
      options = [ "subvolid=5" "subvol=/" ];
    };

  swapDevices = [
    {
        device = "/swap/swapfile";
        size = 1024 * 24;
    }
  ];
  services.btrfs.autoScrub =
  {
    enable = true;
    interval = "weekly";
    fileSystems = [ "/home" "/nix" "/persistent" "/.snapshots" "/root" "/swap" ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
